Update aquasec.yaml

diff --git a/.github/workflows/aquasec.yaml b/.github/workflows/aquasec.yaml
--- a/.github/workflows/aquasec.yaml
+++ b/.github/workflows/aquasec.yaml
@@ -4,14 +4,18 @@ on:
     branches:
       - main
 jobs:
-  build:
-    name: Build
+  checkout:
+    name: Checkout
     runs-on: ubuntu-18.04
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
-
-      - name: Run Trivy vulnerability scanner in IaC mode
+      - name: Login to DockerHub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+      - name: Run Trivy vulnerability scanner - FS mode
         uses: aquasecurity/trivy-action@master
         with:
           scan-type: 'fs'
@@ -24,3 +28,25 @@ jobs:
           TRIVY_RUN_AS_PLUGIN: 'aqua'
           TRIGGERED_BY: 'PUSH'
           GITHUB_TOKEN: ${{ github.token }}
+      - name: Build and push
+        uses: docker/build-push-action@v3
+        with:
+          push: true
+          tags: "arunrana14/graphql-vuln:${{ github.sha }}"
+      - name: Manifest Generation
+        run: |
+          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+          if ! cat install.sh.checksum | shasum -a 256 ; then
+            echo "install.sh checksum failed"
+            exit 1
+          fi
+          sh install.sh
+          rm install.sh install.sh.checksum
+          billy generate \
+              --access-token "${{ secrets.GITHUB_TOKEN }}" \
+              --aqua-key "${{ secrets.AQUA_KEY }}" \
+              --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+
+              # The docker image name:tag of the newly built image
+              --artifact-path "arunrana14/graphql-vuln:${{ github.sha }}"
